---
openapi: 3.0.2
info:
    title: hmsidm-backend
    description: Backend API for hmsidm service
    contact: {}
    version: 1.0.0
servers:
    - description: Production
      url: /api/hmsidm/v1
    - description: Beta
      url: /beta/api/hmsidm/v1
    - description: Preview
      url: /preview/api/hmsidm/v1
paths:
    /domains:
        description: It store the necessary information about a domain that will let manage them
        summary: Domain resource
        get:
            description: |-
                For the current organization, list all the domains that
                are being managed from console.dot
            summary: List domains in the organization
            operationId: listDomains
            parameters:
                - name: offset
                  description: pagination offset
                  required: false
                  schema:
                      type: integer
                  examples:
                      Default offset:
                          value: 0
                      Page 2 for pages of 10 items:
                          value: 10
                  in: query
                - name: limit
                  description: Number of items per page
                  required: false
                  schema:
                      type: integer
                  examples:
                      15 items per page:
                          value: 15
                      Default value:
                          value: 10
                  in: query
            responses:
                '200':
                    $ref: '#/components/responses/ListDomainsResponse'
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - resources
        parameters:
            - name: X-Rh-Insights-Request-Id
              description: Request id for distributed tracing.
              required: false
              schema:
                  type: string
              in: header
        post:
            description: Create a domain in the current organization.
            summary: Create a domain.
            operationId: createDomain
            requestBody:
                description: Domain object to be created.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateDomain'
            responses:
                '201':
                    $ref: '#/components/responses/CreateDomainResponse'
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - resources
    /domains/{uuid}:
        description: Specific operations on an existing domain to read, update or delete it.
        summary: Operations on a specific domain
        delete:
            description: Delete an existing domain from the current organization.
            summary: Delete domain.
            operationId: deleteDomain
            responses:
                '204':
                    description: Returned when the resource was deleted.
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - resources
        get:
            description: Request the information for a specific domain of our organization.
            summary: Read a domain.
            operationId: readDomain
            responses:
                '200':
                    $ref: '#/components/responses/ReadDomainResponse'
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - resources
        parameters:
            - name: X-Rh-Insights-Request-Id
              description: Request id for distributed tracing.
              required: false
              schema:
                  type: string
              in: header
            - name: uuid
              description: The uuid that identify the domain.
              required: true
              schema:
                  type: string
              examples:
                  a random uuid generated by 'uuid' command:
                      value: '"2e8ce5a6-b370-11ed-9330-482ae3863d30"'
              in: path
    /domains/{uuid}/register:
        description: First registration to update the IPA domain information.
        summary: Register domain information throw the ipa-hcc agent.
        parameters:
            - name: X-Rh-Insights-Request-Id
              description: Request id
              required: true
              schema:
                  type: string
              in: header
            - name: X-Rh-Idm-Registration-Token
              description: One-time password to authenticate domain registration with ipa-hcc command.
              required: true
              schema:
                  type: string
              in: header
            - name: uuid
              description: uuid for the IPA domain.
              required: true
              schema:
                  type: string
              examples:
                  uuid:
                      value: 08363cd4-bea8-11ed-b83f-482ae3863d30
              in: path
            - name: X-Rh-Idm-Version
              description: ipa-hcc agent version
              required: true
              schema:
                  type: string
              in: header
        put:
            description: |-
                Use the one time use token to update the initial information for
                a rhel-idm domain.
            summary: Update a domain.
            operationId: registerDomain
            requestBody:
                description: Information for an IPA domain so it is updated from the ipa-hcc agent.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Domain'
            responses:
                '200':
                    $ref: '#/components/responses/RegisterDomainResponse'
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '403':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - actions
    /domains/{uuid}/update:
        description: Update the rhel-idm domain information.
        summary: Update domain information throw the ipa-hcc agent.
        parameters:
            - name: X-Rh-Insights-Request-Id
              description: Request id
              required: true
              schema:
                  type: string
              in: header
            - name: uuid
              description: uuid for the IPA domain.
              required: true
              schema:
                  type: string
              examples:
                  uuid:
                      value: 08363cd4-bea8-11ed-b83f-482ae3863d30
              in: path
            - name: X-Rh-Idm-Version
              description: ipa-hcc agent version
              required: true
              schema:
                  type: string
              in: header
        put:
            description: Update the initial information for a rhel-idm domain.
            summary: Update a previously registered domain.
            operationId: updateDomain
            requestBody:
                description: Information for an IPA domain so it is updated from the ipa-hcc agent.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Domain'
            responses:
                '200':
                    $ref: '#/components/responses/UpdateDomainResponse'
                '400':
                    $ref: '#/components/responses/ErrorResponse'
                '403':
                    $ref: '#/components/responses/ErrorResponse'
                '404':
                    $ref: '#/components/responses/ErrorResponse'
            security:
                - x-rh-identity: []
            tags:
                - actions
    /host-conf/{fqdn}:
        description: Endpoint used by host vm for auto-enrollment.
        summary: Autoenroll host vm endpoint.
        parameters:
            - name: X-Rh-Insights-Request-Id
              description: Unique request id for distributing tracing.
              required: false
              schema:
                  type: string
              in: header
            - name: fqdn
              description: The full qualified domain name of the host.
              required: true
              schema:
                  type: string
              in: path
        post:
            description: Action to retrieve the host information for the host vm being enrolled.
            summary: Get host vm information.
            operationId: hostConf
            requestBody:
                description: Required information to take the action.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HostConf'
                        examples:
                            demo request:
                                value:
                                    fqdn: host1.domain.example
                                    subscription_manager_id: c3ac4b91-27cc-422c-a283-42aadfe730af
            responses:
                '200':
                    $ref: '#/components/responses/HostConfResponse'
            security:
                - x-rh-identity: []
            tags:
                - actions
components:
    responses:
        CreateDomainResponse:
            description: Response when a domain has been created.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Domain'
            headers:
                X-Rh-Idm-Rhel-Idm-Token:
                    schema:
                        type: string
        ErrorResponse:
            description: Error response for some operation.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Errors'
        HostConfResponse:
            description: Response for the HostConf action.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/HostConfResponseSchema'
        ListDomainsResponse:
            description: It represent the response for a list of domains query.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/ListDomainsResponseSchema'
        ReadDomainResponse:
            description: This represent the response for a specific domain.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Domain'
        RegisterDomainResponse:
            description: Response for the domain register operation.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Domain'
        UpdateDomainResponse:
            description: Response for the domain update operation.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Domain'
    schemas:
        CreateDomain:
            title: Root Type for DomainResponse
            description: A domain resource
            type: object
            required:
                - auto_enrollment_enabled
                - description
                - domain_type
                - title
            additionalProperties: false
            properties:
                title:
                    description: the title for the entry
                    type: string
                description:
                    description: Human readable description for this domain.
                    type: string
                    example: This is my awesome domain description.
                auto_enrollment_enabled:
                    description: Enable or disable host vm auto-enrollment for this domain
                    type: boolean
                    example: 'true'
                domain_type:
                    description: Type of this domain. Currently only rhel-idm is supported.
                    type: string
                    enum:
                        - rhel-idm
                    example: rhel-idm
            example:
                title: My Domain Example Title
                description: My Domain Example Description
                type: rhel-idm
                auto_enrollment_enabled: true
        CreateDomainIpa:
            title: Root Type for ResponseIpaObject
            description: Options for ipa domains
            type: object
            required:
                - ca_certs
                - realm_domains
                - realm_name
            additionalProperties: false
            properties:
                servers:
                    description: List of auto-enrollment enabled servers for this domain.
                    type: array
                    items:
                        $ref: '#/components/schemas/CreateDomainIpaServer'
                    example: '["server1.mydomain.example","server2.mydomain.example"]'
                ca_certs:
                    description: A base64 representation of all the list of chain of certificates, including the server ca.
                    type: array
                    items:
                        $ref: '#/components/schemas/CreateDomainIpaCert'
                    example: >-
                        [
                          {
                            "nickname": "MYDOMAIN.EXAMPLE IPA CA",
                            "issuer": "CN=Certificate Authority,O=MYDOMAIN.EXAMPLE",
                            "subject": "CN=Certificate Authority,O=MYDOMAIN.EXAMPLE",
                            "serial_number": "1",
                            "not_before": "2023-01-31T13:23:36Z",
                            "not_after": "2023-01-31T13:23:36Z",
                            "pem": "-----BEGIN CERTIFICATE-----\nMII...\n-----END CERTIFICATE-----\n"
                          }
                        ]
                realm_domains:
                    description: TODO What is the meaning of this field.
                    type: array
                    items:
                        type: string
                realm_name:
                    description: The kerberos realm name associated to the IPA domain.
                    type: string
                    example: MYDOMAIN.EXAMPLE
        CreateDomainIpaCert:
            title: Root Type for CreateDomainIpaCert
            description: Represent a certificate item in the cacerts list for the Ipa domain type.
            type: object
            additionalProperties: false
            properties:
                issuer:
                    type: string
                nickname:
                    type: string
                not_after:
                    type: string
                    format: date-time
                not_before:
                    type: string
                    format: date-time
                pem:
                    type: string
                serial_number:
                    type: string
                subject:
                    type: string
        CreateDomainIpaServer:
            title: Root Type for CreateDomainIpaServer
            description: Server schema for an entry into the Ipa domain type
            type: object
            required:
                - ca_server
                - fqdn
                - hcc_enrollment_server
                - hcc_update_server
                - pkinit_server
                - subscription_manager_id
            additionalProperties: false
            properties:
                ca_server:
                    type: boolean
                    example: 'true'
                fqdn:
                    type: string
                    example: server1.mydomain.example
                hcc_enrollment_server:
                    type: boolean
                    example: 'true'
                hcc_update_server:
                    type: boolean
                    example: 'true'
                pkinit_server:
                    type: boolean
                    example: 'true'
                subscription_manager_id:
                    type: string
                    example: 03965a2c-bd24-11ed-968d-482ae3863d30
            example:
                ca_server: true
                fqdn: ipaserver.mydomain.example
                hcc_enrollment_server: true
                hcc_update_server: true
                pkinit_server: true
                subscription_manager_id: 03965a2c-bd24-11ed-968d-482ae3863d30
        Domain:
            title: Root Type for DomainResponse
            description: A domain resource
            type: object
            required:
                - domain_name
                - domain_type
            additionalProperties: false
            properties:
                title:
                    description: Title to describe the domain.
                    type: string
                description:
                    description: Human readable description abou the domain.
                    type: string
                auto_enrollment_enabled:
                    description: Enable or disable host vm auto-enrollment for this domain
                    type: boolean
                    example: 'true'
                domain_id:
                    description: Internal id for this domain
                    type: string
                    maxLength: 36
                    minLength: 36
                    example: 1aa15eae-a88b-11ed-a2cb-482ae3863d30
                domain_name:
                    description: Domain name
                    type: string
                    pattern: ^[a-z0-9\.\-]+$
                    example: mydomain.example
                domain_type:
                    description: Type of this domain. Currently only rhel-idm is supported.
                    type: string
                    enum:
                        - rhel-idm
                    example: rhel-idm
                rhel-idm:
                    $ref: '#/components/schemas/DomainIpa'
            example:
                auto_enrollment_enabled: true
                domain_description: My awesome domain description.
                domain_id: 1aa15eae-a88b-11ed-a2cb-482ae3863d30
                domain_name: mydomain.example
                domain_type: rhel-idm
                ipa:
                    ca_list: []
                    client_options: {}
                    realm_name: IPA.EXAMPLE
                    server_list:
                        - server1.mydomain.example
                        - Server2.mydomain.example
        DomainIpa:
            title: Root Type for ResponseIpaObject
            description: Options for ipa domains
            type: object
            required:
                - ca_certs
                - realm_domains
                - realm_name
                - servers
            additionalProperties: false
            properties:
                servers:
                    description: List of auto-enrollment enabled servers for this domain.
                    type: array
                    items:
                        $ref: '#/components/schemas/DomainIpaServer'
                ca_certs:
                    description: A base64 representation of all the list of chain of certificates, including the server ca.
                    type: array
                    items:
                        $ref: '#/components/schemas/DomainIpaCert'
                    example: >-
                        [
                          {
                            "nickname": "MYDOMAIN.EXAMPLE IPA CA",
                            "issuer": "CN=Certificate Authority,O=MYDOMAIN.EXAMPLE",
                            "subject": "CN=Certificate Authority,O=MYDOMAIN.EXAMPLE",
                            "serial_number": "1",
                            "not_before": "2023-01-31T13:23:36Z",
                            "not_after": "2023-01-31T13:23:36Z"
                            "pem": "-----BEGIN CERTIFICATE-----\nMIIE...\n-----END CERTIFICATE-----\n",
                          }
                        ]
                locations:
                    description: List of allowed locations
                    type: array
                    items:
                        $ref: '#/components/schemas/DomainIpaLocation'
                realm_domains:
                    description: List of realm associated to the IPA domain.
                    type: array
                    items:
                        type: string
                realm_name:
                    description: The kerberos realm name associated to this IPA domain.
                    type: string
                    maxLength: 253
                    minLength: 3
                    pattern: ^[A-Z0-9\.\-]+$
                    example: MYDOMAIN.EXAMPLE
        DomainIpaCert:
            title: Root Type for CreateDomainIpaCert
            description: Represent a certificate item in the cacerts list for the Ipa domain type.
            type: object
            required:
                - issuer
                - nickname
                - not_after
                - not_before
                - pem
                - serial_number
                - subject
            additionalProperties: false
            properties:
                issuer:
                    type: string
                    example: CN=Certificate Authority,O=MYDOMAIN.EXAMPLE
                nickname:
                    type: string
                    example: MYDOMAIN.EXAMPLE IPA CA
                not_after:
                    type: string
                    format: date-time
                    example: ''
                not_before:
                    type: string
                    format: date-time
                    example: ''
                pem:
                    type: string
                    example: '-----BEGIN CERTIFICATE-----\nMII...\n-----END CERTIFICATE-----\n'
                serial_number:
                    type: string
                    example: '1'
                subject:
                    type: string
                    example: CN=Certificate Authority,O=MYDOMAIN.EXAMPLE
        DomainIpaLocation:
            title: Root Type for DomainIpaLocation
            description: Represent a location for rhel-idm instance.
            type: object
            required:
                - name
            properties:
                name:
                    type: string
                description:
                    description: Location description.
                    type: string
            example:
                name: boston
                description: Location at Boston
        DomainIpaServer:
            title: Root Type for CreateDomainIpaServer
            description: Server schema for an entry into the Ipa domain type.
            type: object
            required:
                - ca_server
                - fqdn
                - hcc_enrollment_server
                - hcc_update_server
                - pkinit_server
            additionalProperties: false
            properties:
                ca_server:
                    type: boolean
                    example: 'true'
                fqdn:
                    type: string
                    example: server1.mydomain.example
                hcc_enrollment_server:
                    type: boolean
                    example: 'true'
                hcc_update_server:
                    type: boolean
                    example: 'true'
                location:
                    description: A location identifier (lower-case DNS label).
                    type: string
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-z][a-z0-9\-]*$
                pkinit_server:
                    type: boolean
                    example: 'true'
                subscription_manager_id:
                    type: string
                    maxLength: 36
                    minLength: 36
                    example: 03965a2c-bd24-11ed-968d-482ae3863d30
            example:
                ca_server: true
                fqdn: ipaserver.mydomain.example
                hcc_enrollment_server: true
                hcc_update_server: true
                location: europe
                pkinit_server: true
                subscription_manager_id: 03965a2c-bd24-11ed-968d-482ae3863d30
        Error:
            title: Root Type for Error
            description: General error schema
            type: object
            required:
                - details
                - id
                - status
                - title
            properties:
                title:
                    description: A human-readable short explanation specific to this occurrence of the problem. This field’s value can be localized.
                    type: string
                    example: Bad request
                details:
                    description: A detailed explanation specific to this occurrence of the problem, e.g. a traceback.
                    type: string
                    example: An error occured at code.go:123.
                id:
                    description: A unique identifier for this particular occurrence of the problem.
                    type: string
                    example: kjuadsfuashwe898w9jf
                status:
                    description: The HTTP status code applicable to this problem, expressed as a string value. This SHOULD be provided.
                    type: integer
                    maxLength: 3
                    maximum: 599
                    minLength: 3
                    minimum: 100
                    readOnly: true
                    example: '400'
            example:
                detail: 'Bad request: additional details: more additional details'
                id: ${X-RH-INSIGHTS-REQUEST-ID}
                status: '400'
        Errors:
            title: Root Type for ErrorResponse
            description: General error response returned by the hmsidm API
            type: object
            properties:
                errors:
                    description: Error objects provide additional information about problems encountered while performing an operation.
                    type: array
                    items:
                        $ref: '#/components/schemas/Error'
                    minItems: 1
                    readOnly: true
                    example: >
                        [
                          {
                            "id": "${X-RH-INSIGHTS-REQUEST-ID}",
                            "status": "400",
                            "detail": "Bad request: additional details: more additional details"
                          }
                        ]
            example:
                errors:
                    - detail: 'Bad request: additional details: more additional details'
                      id: ${X-RH-INSIGHTS-REQUEST-ID}
                      status: '400'
        HostConf:
            title: Root Type for HostConf
            description: Represent the request payload for the /hostconf/:fqdn endpoint.
            type: object
            properties:
                fqdn:
                    description: The full qualified domain name of the host vm that is being enrolled.
                    type: string
                    example: '"myhost.domain.example"'
                subscription_manager_id:
                    description: The id for the subscription manager.
                    type: string
                    example: '"c3ac4b91-27cc-422c-a283-42aadfe730af"'
            example:
                fqdn: host1.domain.example
                subscription_manager_id: c3ac4b91-27cc-422c-a283-42aadfe730af
        HostConfIpa:
            title: Root Type for ResponseIpaObject
            description: Options for ipa domains
            type: object
            required:
                - ca_certs
            properties:
                ca_certs:
                    description: List of certificate data.
                    type: array
                    items:
                        $ref: '#/components/schemas/CreateDomainIpaCert'
                realm_domains:
                    description: List of certificate data.
                    type: array
                    items:
                        type: string
                    example: '["mydomain.example"]'
                realm_name:
                    description: The realm name for the domain
                    type: string
                    example: IPA.EXAMPLE
                server_list:
                    description: List of auto-enrollment enabled servers for this domain.
                    type: array
                    items:
                        type: string
                    example: '["server1.mydomain.example","server2.mydomain.example"]'
            example:
                ca_list: base64
                realm_name: IPA.EXAMPLE
                server_list:
                    - server1.mydomain.example
                    - server2.mydomain.example
        HostConfResponseSchema:
            title: Root Type for HostConfResponse
            description: >-
                The response for the action to retrieve the host vm information
                when
                it is being enrolled. This action is taken from the host vm.
            type: object
            properties:
                domain_name:
                    type: string
                domain_type:
                    type: string
                ipa:
                    type: object
                    properties:
                        ca_cert:
                            type: string
                        realm_name:
                            type: string
                        server_list:
                            type: array
                            items:
                                type: string
            example:
                domain_name: domain.example
                domain_type: rhel-idm
                rhel-idm:
                    ca_cert: |
                        -----BEGIN CERTIFICATE-----
                        MII...
                        -----END CERTIFICATE-----
                    realm_name: DOMAIN.EXAMPLE
                    server_list:
                        - ipaserver.domain.example
        ListDomainsData:
            title: Root Type for ListDomainsData
            description: The data listed for the domains.
            type: object
            required:
                - auto_enrollment_enabled
                - description
                - domain_id
                - domain_name
                - domain_type
                - title
            additionalProperties: false
            properties:
                title:
                    description: Human-friendly title for the domain entry.
                    type: string
                description:
                    description: Human-readable description of the domain entry.
                    type: string
                auto_enrollment_enabled:
                    type: boolean
                domain_id:
                    type: string
                domain_name:
                    type: string
                domain_type:
                    type: string
                    enum:
                        - rhel-idm
            example:
                auto_enrollment_enabled: true
                domain_id: 1aa15eae-a88b-11ed-a2cb-482ae3863d30
                domain_name: mydomain.example
                domain_type: rhel-idm
        ListDomainsResponseSchema:
            title: Root Type for ListDomains
            description: Represent a paginated result for a list of domains
            type: object
            required:
                - data
                - links
                - meta
            additionalProperties: false
            properties:
                data:
                    description: The content for this page.
                    type: array
                    items:
                        $ref: '#/components/schemas/ListDomainsData'
                links:
                    $ref: '#/components/schemas/PaginationLinks'
                meta:
                    $ref: '#/components/schemas/PaginationMeta'
            example:
                data:
                    - auto_enrollment_enabled: true
                      domain_id: 1aa15eae-a88b-11ed-a2cb-482ae3863d30
                      domain_name: mydomain.example
                      domain_type: rhel-idm
                links:
                    first: /api/idm/v1/domains?limit=10&offset=0
                    last: /api/idm/v1/domains?limit=10&offset=10
                    next: /api/idm/v1/domains?limit=10&offset=10
                    previous: /api/idm/v1/domains?limit=10&offset=0
                meta:
                    count: 1
        PaginationLinks:
            title: Root Type for PaginationLinks
            description: Represent the navigation links for the data paginated.
            type: object
            additionalProperties: false
            properties:
                first:
                    description: Reference to the first page of the request.
                    type: string
                last:
                    description: Reference to the last page of the request.
                    type: string
                next:
                    description: Reference to the next page of the request.
                    type: string
                previous:
                    description: Reference to the previous page of the request.
                    type: string
            example:
                first: /api/idm/v1/domains?limit=10&offset=0
                last: /api/idm/v1/domains?limit=10&offset=10
                next: /api/idm/v1/domains?limit=10&offset=10
                previous: /api/idm/v1/domains?limit=10&offset=0
        PaginationMeta:
            title: Root Type for PaginationMeta
            description: Metadata for the paginated responses.
            type: object
            required:
                - count
                - limit
                - offset
            additionalProperties: false
            properties:
                count:
                    description: total records in the collection.
                    type: integer
                    format: int64
                    readOnly: false
                    example: '1'
                limit:
                    description: Number of items per page.
                    type: integer
                    readOnly: false
                offset:
                    description: Initial record of the page.
                    type: integer
                    readOnly: false
            example:
                count: 1
                limit: 10
                offset: 0
        RegisterDomain:
            title: Root Type for DomainResponse
            description: A domain resource
            type: object
            additionalProperties: false
            allOf:
                - $ref: '#/components/schemas/Domain'
        ResponseDomain:
            title: Root Type for DomainResponse
            description: A domain resource
            type: object
            additionalProperties: false
            allOf:
                - $ref: '#/components/schemas/Domain'
            example:
                auto_enrollment_enabled: true
                domain_description: My awesome domain description.
                domain_id: 1aa15eae-a88b-11ed-a2cb-482ae3863d30
                domain_name: mydomain.example
                domain_type: rhel-idm
        RhelIdmToken:
            title: Root Type for RhelIdmToken
            description: Represent a rhel-idm token which allow register the domain information.
            type: object
            properties:
                expiration:
                    type: string
                    format: date-time
                secret:
                    type: string
        UpdateDomain:
            title: Root Type for DomainResponse
            description: Update a domain resource
            type: object
            additionalProperties: false
            allOf:
                - $ref: '#/components/schemas/Domain'
    securitySchemes:
        x-rh-identity:
            name: X-Rh-Identity
            description: Base64-encoded JSON identity header provided by 3Scale. It contains type (System, User), org_id, and either username or certificate CN.
            type: apiKey
            in: header
security:
    - x-rh-identity: []
tags:
    - name: resources
      description: CRUD operation on defined resources
    - name: actions
      description: Endpoints no directly related with resources but model actions with the API
